const RATE_GET_ALL ="RATE_GET_ALL";
const ERROR_RATE ="ERROR_RATE";
const RATE_SINGLE_RECORD_DETAILS="RATE_SINGLE_RECORD_DETAILS";
const ADD_RATE="ADD_RATE";
const UPDATE_RATE="UPDATE_RATE";
const DELETE_RATE="DELETE_RATE"

export default () => {
    return {
        RATE_GET_ALL,
        ERROR_RATE,
        RATE_SINGLE_RECORD_DETAILS,
        ADD_RATE,
        UPDATE_RATE,
        DELETE_RATE
    }
}
