
const GET_USER_DETAILS_DATA = "GET_USER_DETAILS_DATA";
const ERROR_USER_DETAILS_DATA = "ERROR_USER_DETAILS_DATA";
const ADD_USER_DETAILS = "ADD_USER_DETAILS";
const EDIT_USER_DETAILS = "EDIT_USER_DETAILS";
const DELETE_USER_DATA = "DELETE_USER_DATA";
const UPDATE_USER_DATA = "UPDATE_USER_DATA";


export default () =>{
    return {
        GET_USER_DETAILS_DATA,
        ERROR_USER_DETAILS_DATA,
        ADD_USER_DETAILS,
        EDIT_USER_DETAILS,
        DELETE_USER_DATA,
        UPDATE_USER_DATA
    }
}